CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk
MACOSX_DEPLOYMENT_TARGET: '10.9'
VER: '16'
VERBOSE_AT: V=1
VERBOSE_CM: VERBOSE=1
YEAR: '2019'
apr: 1.6.3
blas_impl: mkl
boost: '1.73'
boost_cpp: '1.73'
bzip2: '1.0'
c_compiler: vs2017
cairo: '1.14'
channel_targets: defaults
cl_version: 19.27.29111
clang_variant: clang
cpu_optimization_target: nocona
cran_mirror: https://mran.microsoft.com/snapshot/2018-01-01
cross_compiler_target_platform: win-32
cxx_compiler: vs2017
cyrus_sasl: 2.1.26
dbus: '1'
expat: '2.2'
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fontconfig: '2.13'
fortran_compiler: intel-fortran
fortran_compiler_version: 2019.0.0
freetype: '2.10'
g2clib: '1.6'
geos: 3.8.0
giflib: '5'
glib: '2'
gmp: '6.1'
gnu: 2.12.2
gst_plugins_base: '1.14'
gstreamer: '1.14'
harfbuzz: '2.4'
hdf4: '4.2'
hdf5: 1.10.6
hdfeos2: '2.20'
hdfeos5: '5.1'
icu: '58'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libdap4: '3.19'
libffi: 3.2.1
libgd: 2.2.5
libgdal: '3.0'
libgsasl: '1.8'
libkml: '1.3'
libnetcdf: '4.6'
libpng: '1.6'
libprotobuf: 3.11.2
libtiff: '4.1'
libwebp: 1.0.0
libxml2: '2.9'
libxslt: '1.1'
llvm_variant: llvm
lua: '5'
lzo: '2'
m2w64_c_compiler: m2w64-toolchain
m2w64_cxx_compiler: m2w64-toolchain
m2w64_fortran_compiler: m2w64-toolchain
macos_machine: x86_64-apple-darwin13.4.0
macos_min_version: '10.9'
mkl: '2019'
mpfr: '4'
noarch_python: python
nodejs: '8.12'
numpy: '1.16'
openblas: 0.3.3
openjpeg: '2.3'
openssl: 1.1.1
perl: '5.26'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
pixman: '0.34'
proj: 6.2.1
proj4: 5.2.0
python: '3.8'
python_impl: cpython
python_implementation: cpython
qtwebkit: 'true'
r_base: '3.4'
r_implementation: mro-base
r_version: 3.5.0
readline: '8.0'
runtime_version: 14.27.29016
rust_compiler: rust
rust_compiler_version: 1.46.0
serf: 1.3.9
sqlite: '3'
target_platform: win-64
tk: '8.6'
tools_version: 14.27.29016
update_version: '5'
vc: '14'
xz: '5'
zip_keys:
- - vc
  - c_compiler
  - cxx_compiler
  - fortran_compiler_version
  - python
  - nodejs
  - geos
zlib: '1.2'
